FROM node:alpine

ARG GCLOUD_PROJECT_ID=webidl-diff
ENV GCLOUD_PROJECT_ID=$GCLOUD_PROJECT_ID

# For fetching dependencies in npm
RUN apk add --no-cache git

# For installing grpc
RUN apk add --no-cache python
RUN apk add --no-cache build-base
